### ISSUE TITLE
命令行模式

### ISSUE THREAD

**Issue by lvzhen** [TIGERB/easy-php#2]
以命令行方式运行时，$_REQUEST将不包含 argv 和 argc 信息；它们将存在于 $_SERVER 数组。

**Comment by TIGERB** [comment]
命令行方式运行,如下：

![image](https://cloud.githubusercontent.com/assets/12149373/26053683/532bfee6-399c-11e7-8831-b03ace9b52da.png)


![image](https://cloud.githubusercontent.com/assets/12149373/26053487/9b429588-399b-11e7-849f-605ea82ebca4.png)
