### ISSUE TITLE
请问下easyphp后面还更新吗?

### ISSUE THREAD

**Issue by chenny** [TIGERB/easy-php#29]
easyphp是一个很棒的现代化框架. 看了下. 架构从出来到现在. 基本上2年没有怎么更新了. 都是维护状态. 
最近想找一个不错的框架,开发也有很多年了. 用过很多框架.也构架过一些框架. 看了你的所有blog,最近的几年在小米成长非常快,已经在深入研究后端相关产业链了. nginx,mysql,redis,http,socket的各种机制了. 对你的框架蛮有期待的. 非常了了解下,后期easyphp的计划?

 目前市面的主流框架(laravel,yii, Symfony)都非常强大,强大到臃肿,各种优雅和语法糖,已经慢到无法直视了. 项目中完全完全不敢用. 好的是产业链强大,有需要的都找的到,但是各种依赖除了问题不可能控制. 
yaf,cphalcon, Swoole都是c扩展框架,性能没得说. 但是不方便扩展,可控性稍弱. 
ci倒是简单,完全可控,性能也行,就是太老. 不符合现代框架了. 
thinkphp国内发展不错,产业链也不错. 但没什么感觉. 
腾讯的biny,其实感觉不错. 没人维护. 
cmlphp好像偏向游戏方向, 之前我们也做游戏. 也是自己的框架,php短连接业务+golang长连接推送系统. 
easyphp总体感觉还不错. 除了性能不错. 简单高效,完全可控,到业务实际开发中,比如mcl,比如考虑到前后端分离思想, 但既然分离. 可以把前后端分开到两个项目里面维护. 就框架而已. 全栈思维能力很不错. 但是项目分开. 更便于团队化维护. 
所以特别期待后面easyphp的发展. 期望能够持续交流

**Comment by TIGERB** [comment]
首先，目前这个easyphp项目的定义：主要是我对那几年php学习的一个思考和输出的过程，它的主要定位是一个学习框架，帮助所有的PHPer快速高效的理解一个php框架的构建过程。

接着，easyphp的未来：会出新的企业级版本，一个轻量、高可扩展、工具化的现代php框架。但是由于目前的工作状态和学习规划(继续往底层、golang学习)，这个事情的就需要在一个恰当的时间发生了。

最后，你的建议：

1. 「但既然分离. 可以把前后端分开到两个项目里面维护.」
答：你的建议没毛病，我说说我当时的想法，上面说了“目前的定位一个学习框架”，所以放在了一起，主要展示给没有前端经验的PHPer，看看现代完整的前后端分离的简单示例，未来的企业级版本是不会包含前端的。

最最后，纠正：

「最近的几年在小米成长非常快」这句话貌似并不是很正确，哈哈哈哈😂

**Comment by chenny** [comment]
感谢你的回复，期待未来的企业版本，思路可以先发出来，大家一起完善.

**Comment by TIGERB** [comment]
好的 后面补一下

**Comment by chenny** [comment]
phalphp设计思想蛮不错，也是前后端分离，专注api，有自动生成api，还带有主流语言的rpc，也是mcl模式，产业链发展的还不错，你可以看看，代码架构和商业模式值得参考，目录架构和代码风格不是我喜欢的

**Comment by TIGERB** [comment]
好的～
