### ISSUE TITLE
关于load自动加载

### ISSUE THREAD

**Issue by chenye2017** [TIGERB/easy-php#31]
项目类的自动加载，（framework/Load.php）这块有两个static 变量$map， $namespaceMap 感觉都没有用到，不知道添加的原因是什么（ps:issure 里面能提这样的问题嘛）

**Comment by TIGERB** [comment]
「issure 里面能提这样的问题嘛」
答：可以
--------
「项目类的自动加载，（framework/Load.php）这块有两个static 变量$map， $namespaceMap 感觉都没有用到，不知道添加的原因是什么」
答：是准备做 namespace和文件路径缓存的。

**Comment by chenye2017** [comment]
hi, 看了你的container 容器，感觉你的容器更像是注册树模式，把需要用到的类对象都保存起来，下次使用的时候直接从里面取，而对于 

class A {
  public function __construct(B $b) {
        echo $b->name;
    }
}
类实例化时候依赖的自动注入没有涉及到，更多的是直接把这个 b手动生成一个object(或者是closure中传入这个参数)，不知道理解对不对

**Comment by TIGERB** [comment]
是
