### ISSUE TITLE
关于异常处理的疑问

### ISSUE THREAD

**Issue by chenny** [TIGERB/easy-php#32]
![image](https://user-images.githubusercontent.com/883329/56275602-99055280-6133-11e9-98d3-db3881c92ef3.png)

我们设计的时候, 为什么要给前端返回不一致的数据格式?

**Comment by TIGERB** [comment]
看了下 当时的设计有问题 欢迎PR👏

**Comment by TIGERB** [comment]
已经修复～

thx~

**Comment by chenny** [comment]
👍👍👍
