### ISSUE TITLE
loadEnv方法转移的意义是？

### ISSUE THREAD

**Issue by chenobdo** [TIGERB/easy-php#4]
在 SHA-1: a3c7685ad999 这个版本之前 loadEnv 方法是在 ConfigHandle类中，在这次的commit中转移到了 Request类中是基于什么样的考虑呢？

**Comment by TIGERB** [comment]
loadEnv的定义是加载环境变量：

之前：
因为如大多数的框架一样我把环境变量存放在.env这个文件，当时对加.env文件身份的定义只是配置文件，所以把加载的过程实现在了ConfigHandle里。

之后：
我觉着这样是有问题的，因为env的定义是环境变量，同样的程序运行于不同的环境下是不同的，它应作为上下文Context的上文来定义更加的合适，就如同$_REQUEST, $_POST, $_GET, $_SERVER,而Request对象就是这里的上文具体的承载者。

**Comment by chenobdo** [comment]
恩，非常感谢。

**Comment by TIGERB** [comment]
客气，互相学习～

开源项目，你也可以贡献你的想法～
