### ISSUE TITLE
ORM的sql builder是不是学laravel的^_^

### ISSUE THREAD

**Issue by rabbitLove520** [TIGERB/easy-php#8]
感觉**Service Container**这一点也是。
Performance的话,我感觉可以和别的框架对比一下,譬如tp和laravel

**Comment by TIGERB** [comment]
哈哈，基本大家都是按设计模式走的，整个框架的一些地方，毋庸置疑有受到我在使用各个框架中优秀的地方的影响，但是内部的实现都是按照我自己的想法实现的～

其次，在
简洁性
面向开发者友好性
上面我都充足的展现了我自己的理解和想法，随着时间的推移，不断去迭代，不断去解决我们开发中的痛点，但是一切都围绕简洁高效却不失优雅为出发点。

非常欢迎大家一起来迭代，去放飞自己的思想～

哈哈～

thx~
