### ISSUE TITLE
webpack output undefined

### ISSUE THREAD

**Issue by Nicksxs** [TIGERB/easy-php#9]
![image](https://user-images.githubusercontent.com/7351669/28147133-03f0d7a0-67b1-11e7-9300-82087c1da08f.png)
![image](https://user-images.githubusercontent.com/7351669/28147193-7351d7f2-67b1-11e7-8eed-22f779123b42.png)

**Comment by TIGERB** [comment]
DOMAIN=http://你的域名 npm run dev 

例如：
```
DOMAIN=http://localhost:666 npm run dev
```

**Comment by Nicksxs** [comment]
但是在public目录下还是没生成dist目录

**Comment by TIGERB** [comment]
dev是开发模式不生成文件；

下面的会生成开发环境的文件：
DOMAIN=http://localhost:666 npm run demo

生产环境：
DOMAIN=http://localhost:666 npm run build

**Comment by Nicksxs** [comment]
这两个我看到了，那如果是开发模式，整个项目要怎么运行呢，在public目录下不生成dist目录和html，前端怎么访问，对于vue这块比较陌生，有点懵

**Comment by TIGERB** [comment]
我看了下在这个项目下运行VUE的开发模式有些问题，之前这块没自测过，不好意思哈，后续会修复。

如果你想了解VUE的开发模式你可以先看下我的这个项目<https://github.com/TIGERB/easy-vue>

主要就是使用webpack-dev-server实现的热加载，就是你开发中修改代码后会自动刷新页面提高开发效率。

**Comment by Nicksxs** [comment]
需要怎么改下，

**Comment by Nicksxs** [comment]
是不是要把index.html放一个别的目录，然后针对dist目录做不同路由

**Comment by TIGERB** [comment]
已修复，更新就好了。

command:

DOMAIN=http://localhost:8080 npm run dev

**Comment by Nicksxs** [comment]
这个默认的就是显示public目录下的文件吗，具体的代码是哪个

**Comment by TIGERB** [comment]
文件都是 frontend下的源码文件，dev编译后的文件是在内存中的
